### ISSUE TITLE
An issue where custom block format is not retained when switching to another format and then back to custom

### ISSUE THREAD

**Issue by kkartch0** [kkartch0/obsidian-gospel-study#61]
I would expect the custom format to not clear unless the user explicitly clears it. Switching between formats should not clear out the custom one.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the GospelStudyPluginSettingTab class to store the custom format separately and preserve it when switching between format options. This ensures that the custom format is not cleared unless explicitly done by the user.

You can review changes in this commit: https://github.com/lkilu6456546/kkartch0-obsidian-gospel-study-61/commit/a18d0f73df891d704139685a11819de928d4fea6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
